title: "Tensors & Quarks"
email: "raahul.thakurr01@gmail.com"
description: "Exploring the intersection of physics and machine learning."

url: "https://www.tensorsandquarks.space"

baseurl: ""

author: "Rahul Thakur"
excerpt_separator: "<!--more-->"

paginate: 5
paginate_path: "/page:num"

plugins:
  - jekyll-paginate
  - jekyll-seo-tag

markdown: kramdown
