title: "Tensors & Quarks"
email: "raahul.thakurr01@example.com"
description: "Exploring the intersection of physics and machine learning."
url: "https://raahul-thakur.github.io"
baseurl: "/tensorandquarks.github.io"



author: "Rahul Thakur"
excerpt_separator: "<!--more-->"

paginate: 5
paginate_path: "/page:num"

plugins:
  - jekyll-paginate
  - jekyll-seo-tag

markdown: kramdown
